eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      
microservice:
  payment-service:
   endpoints:
    endpoint:
     uri:http://PAYMENT-SERVICE:9091/payments     

  order-service:
   endpoints:
    endpoint:
      uri:http://ORDER-SERVICE:9090/orders
  
