eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      
microservice:
  demo:
   endpoints:
    endpoint:
      uri:http://localhost:8086/demo
  hystrix:
   endpoints:
    endpoint:
     uri:http://localhost:8080/demo      
